.TH onionconfig 1 "6 Feburary 2019" "0.1"
.SH NAME
onionconfig - configuration program for onionchat

.SH SYNOPSIS
.B onionchat

.SH DESCRIPTION
.B Onionconfig
writes or edits the configuration for onionchat.
.B Onionconfig
only writes to the locations where onionchat is looking for the config file and outputs in a predetermined form that oninchat is expecting.

.SH OPTIONS
Onion config takes no options

.SH FILES
.IR ~/.config/onionchat/config | ~/.onionchat/config | ~/.onionconfig |
.RS
.B onionconfig
will write to the selected file
.RE

.SH BUGS
None known at this time
.SH SEE ALSO
onionchat(1)

.SH AUTHOR
Colton Beck
