.TH onionchat 1 "5 June 2018" "0.1"
.SH NAME
onionchat - chat system using randomized onion routing
.SH SYNOPSIS
onionchat [-s] [-h ip]
.SH DESCRIPTION
Onionchat is a chat system that uses randomized onion routing to encrypt user communication. Onionchat can be run in a headless mode for embeded nodes to increase the security of the network.
.SH OPTIONS
.IP -s
Start as server. System needs one server to initalize the user list. Acting server will migrate when current server leaves the network.
.IP -h "ip"
Start in headless mode. Used for embedded applications where the frontend is unneeded.
.SH BUGS
None known at this time
.SH AUTHOR
Colton Beck
